#159236203 Relate WorkoutSession & WorkoutLog Models.
andela/wg-wits pull request #15
Opened 2018-08-09 09:32 UTC by RrNn

#### What does this PR do?
- This PR creates a foreign key `session_id` on the WorkoutLog model referencing the WorkoutSession 
### How should this be manually tested?
-  Clone the application as guided in the README.
- Create virtual environment and activate it.
- `pip install -r requirements_devel.txt`
- `pip install psycopg2_binary`
- `-invoke create-settings --settings-path ./settings.py`
- `npm install bower`
- `sudo python manage.py bower_install --allow-root`
- `invoke bootstrap-wger --settings-path ./settings.py --no-start-server`
- `git checkout ch-wrkoutlog-sessn-rlation-159236203`
- Make and run the migrations by:
* `python manage.py makemigrations`
* `pyothn manage.py migrate`
- Login the application as any user and add a workout  at `http://127.0.0.1:8000/en/workout/overview`
- Add a weight log to that day and check out the database tables `manager_workoutlog` and `manager_workoutsession`. Notice the primary key on the `manager_workoutsession` table being referenced by the `session_id` column on the `manager_workoutlog` table.
#### Relevant Pivotal Tracker story.
[#159236203](https://www.pivotaltracker.com/story/show/159236203)

2018-08-09 13:42 UTC, solnsubuga requested changes
Please change the name of instance of WorkoutSession from `session_id` to `session`.

2018-08-09 13:42 UTC, solnsubuga commented on wger/manager/models.py
> +    session_id = models.ForeignKey('WorkoutSession', null=True, blank=True, to_field='id')
@RrNn  you cannot name this `session_id` because in this case, it's an instance of a WorkoutSession.

2018-08-09 14:29 UTC, RrNn commented
@solnsubuga done.

2018-08-09 14:31 UTC, solnsubuga commented
@RrNn  I don't see the updated migration.

2018-08-09 16:21 UTC, solnsubuga approved these changes

2018-08-09 17:56 UTC, wasswa-derick approved these changes
LGTM

2018-08-10 06:37 UTC, RrNn commented on wger/manager/migrations/0010_auto_20180809_1739.py
> +            new_name='session',
@solnsubuga, right there

2018-11-13 10:56 UTC, merged