#159396462 Add badges and Travis integration
andela/wg-wits pull request #2
Opened 2018-07-31 06:49 UTC by ja-odur

#### What does this PR do?
* Adds Travis integration and badges to the develop branch.

#### Description of Task to be completed?
* Add Travis Integration
* Add Build, Test Coverage, and Maintainanbility badges.
#### What are the relevant pivotal tracker stories?
[159396462](https://www.pivotaltracker.com/story/show/159396462)

2018-07-31 06:52 UTC, solnsubuga commented
@ja-odur the badges are not being displayed, they are just links. See attached image. Check on this.
<img width="963" alt="screen shot 2018-07-31 at 09 51 02" src="https://user-images.githubusercontent.com/23418080/43442686-6437cd34-94a7-11e8-9300-b9eeba9e1df5.png">

2018-07-31 07:12 UTC, solnsubuga requested changes

2018-07-31 07:12 UTC, solnsubuga commented on wger/settings_global.py
> +#    'jquery#2.1.x',
@ja-odur please remove these commented out lines (106 -116) since you already have them covered above.

2018-07-31 07:57 UTC, solnsubuga approved these changes

2018-07-31 09:10 UTC, lym commented
@ja-odur Add a _how can this be manually tested_ section and screen shots of how the badges are being rendered in the README in your PR description.

2018-07-31 13:43 UTC, lym commented
@ja-odur Please add the project name to the README, just before the badges, as is done in the picture below.

![image](https://user-images.githubusercontent.com/783970/43463217-bcb8ebda-94e0-11e8-8fd1-c49c0442009a.png)

2018-08-01 09:36 UTC, wasswa-derick reviewed
@ja-odur 
I have reviewed the PR. It seems to be a great output save for the concern I have about the badges.

In the ReadMe, they are included as images
-  image:: https://travis-ci.org/andela/wg-wits.svg?branch=develop
    :target: https://travis-ci.org/andela/wg-wits

I have made some reading that github could sometimes cache those image badges and even when the metrics change, the badge remains the same. https://github.com/github/markup/issues/224

I would recommend including the Markdown badge that may not be cached for the most part. You can get the markdown by clicking on the badges and look for the representation of that badge in the markdown format.

2018-08-01 09:45 UTC, ja-odur commented
@wasswa-derick,
The README is in the .rst format which means the markdown format cannot be rendered in it.
I am still researching on how to prevent the cache issue but those badges are the generated RST formats from both coveralls and codeclimate.

2018-08-01 11:20 UTC, RrNn commented
The badges look good to me now. Me I approve merging

2018-08-02 11:06 UTC, lym commented
@ja-odur Update the screenshot and description to exclude information about Gitter.

2018-08-02 13:31 UTC, merged