Create users via REST API
andela/wg-wits pull request #20
Opened 2018-08-16 08:14 UTC by wasswa-derick

#### What does this PR do?
* Allow users to create users via REST API

#### Description of Task to be completed?
*  Create a permission for REST API user creation
* Admin grants permissions to the users to create users via the REST API. 
* Add special flags to the user profile to identify users created via the REST API or not.
* Create model to show REST API users relationship with their creators.
* Create a serializer for the user objects
* Create Viewset for REST API user creation
* Create the private API endpoint for user registration
* List all REST API users

#### How should this be manually tested?
* Clone the project, ```https://github.com/andela/wg-wits.git```.
* In your terminal, ```cd wg-wits```
* Checkout to the ```ft-api-create-users-159236198``` branch.
* In the project directory, create a virtual environment and activate it: run ```virtualenv -p python3 venv-django``` then ```source venv-django/bin/activate```
* Install requirements ```pip install -r requirements_devel.txt```
* Run ```python manage.py migrate``` to  include the new migrations.
* Serve the application ```python manage.py runserver```
* Run the command ```python manage.py add-user-rest-api 'username' --username``` or ```python manage.py add-user-rest-api 'email' --email``` to grant permissions to a user to create users.
* In the browser, visit the endpoint for the users with, ```http://127.0.0.1:8000/api/v2/users/```
* This shall list all the users available.
* In the input fields at the bottom of the screen, enter data in the fields and post.
* To list the users create via REST API, run this command ```python manage.py list-user-rest-api```

#### What are the relevant pivotal tracker stories?
[#159236198](https://www.pivotaltracker.com/story/show/159236198)

#### Screenshots (if appropriate)

* Accessing user creation without permission

<img width="1402" alt="screen shot 2018-08-16 at 11 07 15" src="https://user-images.githubusercontent.com/39955231/44196543-e2387900-a144-11e8-84e4-df34776fd70a.png">

* Granting user creation permission to a user

<img width="1310" alt="screen shot 2018-08-16 at 11 08 43" src="https://user-images.githubusercontent.com/39955231/44196545-e2d10f80-a144-11e8-88cc-94a80e9f374c.png">

* Users Endpoint

<img width="1675" alt="screen shot 2018-08-16 at 11 05 59" src="https://user-images.githubusercontent.com/39955231/44196540-e19fe280-a144-11e8-9fbd-bab6c6040171.png">

* Creating a user

<img width="1012" alt="screen shot 2018-08-16 at 11 06 35" src="https://user-images.githubusercontent.com/39955231/44196541-e2387900-a144-11e8-80ae-80d5563a6533.png">

* User Created

<img width="1479" alt="screen shot 2018-08-16 at 11 06 48" src="https://user-images.githubusercontent.com/39955231/44196542-e2387900-a144-11e8-8490-506e7cd1d19b.png">

* List REST API users

<img width="884" alt="screen shot 2018-08-16 at 11 09 13" src="https://user-images.githubusercontent.com/39955231/44196546-e369a600-a144-11e8-9fb0-e037ed2f4429.png">

2018-08-16 13:08 UTC, solnsubuga commented
@wasswa-derick Please ensure apps cannot create users with already existing emails.

2018-08-16 14:33 UTC, RrNn requested changes

2018-08-16 14:33 UTC, RrNn commented on wger/core/management/commands/add-user-rest-api.py
> +            user = User.objects.get(email=email)
Catch User Doesn't Exist exception

2018-08-16 14:33 UTC, RrNn commented on wger/core/management/commands/add-user-rest-api.py
> +            user = User.objects.get(email=email)
Replace the 3 exclamation marks with one and don't put a space between the last letter and the exclamation mark.

2018-08-16 14:33 UTC, RrNn commented on wger/core/management/commands/list-user-rest-api.py
> +            self.stdout.write('Username: {} , Email: {}' . format(user.username, user.email))
`Email: {}' . format` Get rid of that space

2018-08-16 18:19 UTC, solnsubuga commented
@wasswa-derick please update the how to manually test this section to include the new instructions.

2018-08-17 10:22 UTC, solnsubuga approved these changes
Looks good.

2018-08-17 10:25 UTC, Yiga-fred commented
LGTM

2018-08-17 11:23 UTC, RrNn approved these changes
LGTM

2018-08-20 09:42 UTC, merged